import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/NavBar";

import Preloader from "./section/PreLoader";
import SmoothScroller from "./components/SmoothScroller";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background">
        <Preloader />
        <NavBar />
        <div id="smooth-wrapper">
          <div id="smooth-content">
            <main>{children}</main>
          </div>
        </div>

        <SmoothScroller />
      </body>
    </html>
  );
}
